# Getting started with TensorFlow (lab1)

## NumPy overwiev

Let's import needed libraries

In [16]:
import numpy as np
import tensorflow as tf

1. Let's create an array to make operations with

In [27]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [48]:
# basic operations with scalars
print(arr1 + 3)
print(arr1**2)

[ 4  5  6  7  8  9 10 11 12 13 14 15]
[  1   4   9  16  25  36  49  64  81 100 121 144]


In [64]:
# basic operations with arrays
print("Sum of array: " + str(np.sum(arr1)))
print("Min value: " + str(np.min(arr1)))
print("Mean of array: " + str(np.mean(arr1)))
print("Median of array: " + str(np.median(arr1)))

Sum of array: 78
Min value: 1
Mean of array: 6.5
Median of array: 6.5


In [61]:
# creating an array of zeros
arr2 = np.zeros(10)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
# creating matrix of ones
arr3 = np.ones((4,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2. Lets use *arange()* and *random()* functions with NumPy

In [65]:
# creating a matrix 3x5 size in interval from 0 to 14
arr4 = np.arange(15).reshape(3, 5)
print(arr4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [66]:
# creating a random matrix and product of two matrix
arr5 = np.random.rand(3,3)
print(np.dot(arr5, arr5))

[[0.44821893 0.89720853 1.2020921 ]
 [0.19369152 0.34974104 0.96997287]
 [0.21008966 0.33919781 1.09824013]]


## TensorFlow overview

1. let's create a basic array of data to make some operation with that

In [90]:
# Creating tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [95]:
#creating tensor of all ones
tensor_zeros = tf.Variable(tf.zeros((4,4,4)))
#creating tensor with normal distribution
tensor_rand_norm = tf.Variable(tf.random.normal((7,7),mean=4, stddev=2))
# creating tensor using uniform distribution
tensor_rand_int = tf.Variable(tf.random.uniform((4,4,4), minval=6, maxval=10, dtype=tf.dtypes.int32, seed=42))
tensor_rand_norm

<tf.Variable 'Variable:0' shape=(7, 7) dtype=float32, numpy=
array([[5.026022  , 5.3273506 , 1.2275047 , 4.2048526 , 2.1088648 ,
        2.2724438 , 1.7091    ],
       [1.0169008 , 3.1463668 , 5.5835104 , 2.1998582 , 5.463565  ,
        4.2202053 , 5.2027893 ],
       [6.696681  , 5.0102015 , 0.8110671 , 3.7025254 , 3.9684732 ,
        5.734307  , 2.0690534 ],
       [3.9662457 , 5.080948  , 0.03965473, 4.7244163 , 5.355527  ,
        4.634552  , 3.0033436 ],
       [3.661502  , 4.6547475 , 2.64708   , 4.899432  , 5.587304  ,
        2.8901892 , 5.6103077 ],
       [1.84389   , 2.0908785 , 2.0789611 , 6.162301  , 4.2339463 ,
        5.4699574 , 5.2972417 ],
       [1.7030954 , 4.5926332 , 7.583365  , 3.2096329 , 7.9143023 ,
        5.169727  , 1.3830512 ]], dtype=float32)>

2. Now we can make some basic operations using TensorFlow

In [97]:
# basic operations
tensor_rand_int * 10

<tf.Tensor: shape=(4, 4, 4), dtype=int32, numpy=
array([[[90, 90, 60, 90],
        [70, 70, 80, 60],
        [70, 80, 80, 60],
        [60, 60, 80, 70]],

       [[90, 70, 60, 70],
        [70, 70, 70, 60],
        [90, 70, 60, 90],
        [80, 60, 70, 60]],

       [[70, 70, 70, 90],
        [60, 70, 90, 90],
        [90, 80, 60, 70],
        [70, 70, 90, 60]],

       [[80, 90, 80, 90],
        [70, 60, 60, 60],
        [90, 80, 80, 60],
        [70, 90, 80, 90]]], dtype=int32)>

In [98]:
# transpose matrix
tf.transpose(tensor_rand_norm[0,3])

<tf.Tensor: shape=(), dtype=float32, numpy=4.2048526>

In [107]:
# update 
tensor_rand_norm[3,3].assign(2.7182)

<tf.Variable 'UnreadVariable' shape=(7, 7) dtype=float32, numpy=
array([[5.026022  , 5.3273506 , 1.2275047 , 4.2048526 , 2.1088648 ,
        2.2724438 , 1.7091    ],
       [1.0169008 , 3.1463668 , 5.5835104 , 2.1998582 , 5.463565  ,
        4.2202053 , 5.2027893 ],
       [6.696681  , 5.0102015 , 0.8110671 , 3.7025254 , 3.9684732 ,
        5.734307  , 2.0690534 ],
       [3.9662457 , 5.080948  , 0.03965473, 2.7182    , 5.355527  ,
        4.634552  , 3.0033436 ],
       [3.661502  , 4.6547475 , 2.64708   , 4.899432  , 5.587304  ,
        2.8901892 , 5.6103077 ],
       [1.84389   , 2.0908785 , 2.0789611 , 6.162301  , 4.2339463 ,
        5.4699574 , 5.2972417 ],
       [1.7030954 , 4.5926332 , 7.583365  , 3.2096329 , 7.9143023 ,
        5.169727  , 1.3830512 ]], dtype=float32)>

In [108]:
#removing parts of tensor
tensor_rand_int = tf.concat([tensor_rand_int[:2], tensor_rand_int[3:]], axis=0) # Remove the 2-rd sub-tensor
tensor_rand_int

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[9, 9, 6, 9],
        [7, 7, 8, 6],
        [7, 8, 8, 6],
        [6, 6, 8, 7]],

       [[9, 7, 6, 7],
        [7, 7, 7, 6],
        [9, 7, 6, 9],
        [8, 6, 7, 6]]], dtype=int32)>

In [110]:
#reshape matrix
tf.reshape(tensor_rand_int,(4,8))

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[9, 9, 6, 9, 7, 7, 8, 6],
       [7, 8, 8, 6, 6, 6, 8, 7],
       [9, 7, 6, 7, 7, 7, 7, 6],
       [9, 7, 6, 9, 8, 6, 7, 6]], dtype=int32)>

In [111]:
tf.constant(np.random.randint(0, 25, size=(5,5,5)))
tf.Variable(np.random.randn(5,5,5))

<tf.Variable 'Variable:0' shape=(5, 5, 5) dtype=float64, numpy=
array([[[ 0.36983312,  0.40041723,  0.60891625,  0.86458655,
         -0.80561246],
        [ 1.24778811,  0.90648663,  0.41888996, -0.68015468,
          1.01881324],
        [ 0.65838267, -0.40789889, -0.90802632,  1.10863676,
         -0.27872799],
        [-0.03443191,  0.01146922,  0.13250903, -1.3287509 ,
         -0.1394355 ],
        [ 1.59925533, -0.21144622, -0.45325456,  0.36166035,
         -0.96936142]],

       [[ 1.08651255, -0.97317851,  0.64140028, -0.116933  ,
         -0.12376117],
        [-0.77433339, -1.73623062, -1.82394871, -1.5265272 ,
          0.22223805],
        [ 0.7286334 , -0.64285394,  1.50004638, -0.54377462,
          0.55840171],
        [ 0.04623751,  0.01883009,  0.338096  , -1.56620177,
          0.81989369],
        [ 0.42883422,  1.03762345, -1.61580344,  0.93963094,
         -0.13917068]],

       [[ 0.34684442, -0.09511668,  0.40929116, -0.57020187,
          0.91287125],
        

3. Let's make operations with tensor using NumPy 

In [112]:
#creating an array between 1 and 13
numpy_A = np.arange(1, 13, dtype=np.int32) 
A = tf.constant(numpy_A,  
                shape=[2,6])
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32),
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=int32)>)